import bcrypt from 'bcryptjs';
const data={
    users:[
        {
            name:'Prakash',
            email:'ponduriprakash7078@gmail.com',
            password:bcrypt.hashSync('admin'),
            isAdmin:true,
        },
        {
            name:'Surya',
            email:'suryaprakash7078@gmail.com',
            password:bcrypt.hashSync('anu'),
            isAdmin:false,
        },
    ],
    hobies:[
        {
            id:1,
            image:"/Hobies/araku.jpeg",
            desc:"Araku",
        },
        {
            id:2,
            image:"/Hobies/araku2.jpeg",
            desc:"Araku",
        },
        {
            id:3,
            image:"/Hobies/araku3.jpeg",
            desc:"Araku",
        },
        {
            id:4,
            image:"/Hobies/frds.jpeg",
            desc:"Araku",
        },
        {
            id:5,
            image:"/Hobies/google.jpg",
            desc:"Araku",
        },
        {
            id:6,
            image:"/Hobies/image1.jpg",
            desc:"Araku",
        },
        {
            id:7,
            image:"/Hobies/image2.jpeg",
            desc:"Araku",
        },
        {
            id:8,
            image:"/Hobies/image3.jpeg",
            desc:"Araku",
        },
        {
            id:9,
            image:"/Hobies/frds.jpeg",
            desc:"friends",
        },
    ],
    others:[
        {
            id:1,
            image:"/Others/NSS1.jpeg",
            desc:"Other hobies"
        },
        {
            id:1,
            image:"/Others/NSS2.jpeg",
            desc:"Other hobies"
        }
    ]
};
export default data;